### PR TITLE
added MET reapplying JEC

### PR DESCRIPTION
**Pull request by ahortian**

### CODE REVIEW

**Comment by grasph** [comment]
Pull done. 

What is the difference between PAT and RECO MET filter?

**Comment by ahortian** [comment]
> > What is the difference between PAT and RECO MET filter? 

Filters for ETmiss cleaning are run at MiniAOD production stage, and saved as a trigger results (an edm::TriggerResults of the RECO or PAT process, depeding on whether MiniAOD was produced simultaneously with RECO or as a separate step).
For more details, please see: https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2015#ETmiss

**Comment by grasph** [comment]
It means that RECO should be used if type-I correction is reapplied. Did I understand it correctly?

If so it would be more convenient to keep a single branch and set in the configuration file the product label depending if type-I corr is reapply or not. What do you think?

**Comment by ahortian** [comment]
> > It means that RECO should be used if type-I correction is reapplied. Did I understand it correctly?

I don't think so. As to my understanding, re-applying the JEC does not affect the met filter. So, this met filter part is actually not relevant to type-I correction. I updated this part just to have better handling of met filter.

Only updates that are relevant to the re-applying the JEC are the commented-out code I use to check the effect.
https://github.com/UGent/Tupel/blob/Tupel_MiniAOD_76x/Tupel/src/Tupel.cc#L839

**Pull request merged**
